version: '3'

services:
  db:
    image: postgres:9.4
    container_name: db
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=teste
    ports:
      - "5432:5432"

  app: 
    build: .
    container_name: app
    tty: true
    volumes:
      - .:/src
    ports:
      - "8888:8888"
    environment:
      - POSTGRESQL_URL=postgres://postgres:root@db:5432/teste?sslmode=disable